spring.cloud.stream:
  function.definition: supplier;processor;sink
  bindings:
    supplier-out-0.destination: messages
    processor-in-0.destination: messages
    processor-out-0.destination: reversed
    sink-in-0.destination: reversed
  kafka.binder.brokers: kafka:9092